version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data   # persist data in a folder
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=arimala
      - POSTGRES_PASSWORD=arimala_pw
      - POSTGRES_DB=arimala_dev
